---
    # --- 1. INTERFACE CHECKOUT ---
    - name: Interface | Search for any existing bridge
      community.routeros.api:
        path: "interface bridge"
        cmd: "print"
      register: existing_bridges

    - name: Interface | Rename default bridge to bridge_lan
      community.routeros.api:
        path: "interface bridge"
        update: >
          .id={{ existing_bridges.msg[0]['.id'] }}
          name={{ router_lan_interface }}
          comment="Managed by Ansible"
      when:
        - existing_bridges.msg | length > 0
        - existing_bridges.msg[0].name != router_lan_interface

    - name: Interface | Get all current bridge ports
      community.routeros.api:
        path: "interface bridge port"
        cmd: "print"
      register: current_bridge_ports

    - name: Interface | Add ports to bridge if not already bridged
      community.routeros.api:
        path: "interface bridge port"
        add: "bridge={{ router_lan_interface }} interface={{ item }}"
      loop: "{{ router_bridge_ports }}"
      # Get current state (current_bridge_port) > Extract 'interface' fields only (map) > Convert to a flat list (list) > Check if target interface is NOT in that list (not in) 
      when: item not in (current_bridge_ports.msg | map(attribute='interface') | list)

    # --- 2. NETWORK CONFIG ---
    - name: Network | Get all current IP addresses
      community.routeros.api:
        path: "ip address"
        cmd: "print"
      register: current_ips

    - name: Network | Set LAN IP Address
      community.routeros.api:
        path: "ip address"
        add: "address={{ router_lan_address }} interface={{ router_lan_interface }}"
      # Get current state (current_ips.msg) > Extract 'address' fields only (map) > Convert to flat list (list) > Check if target address is NOT in that list (not in)
      when: router_lan_address not in (current_ips.msg | map(attribute='address') | list)
    
      # --- 3. DHCP CONFIG ---
    - name: DHCP | Get current DHCP networks
      community.routeros.api:
        path: "ip dhcp-server network"
        cmd: "print"
      register: current_dhcp_networks

    - name: DHCP | Ensure DHCP network exist
      community.routeros.api:
        path: "ip dhcp-server network"
        add:
          # Get address from router_lan_address (ipaddr)
          address: "{{ router_lan_address | ipaddr('network/prefix') }}"
          # Get gateway from router_lan_address (ipaddr)
          gateway: "{{ router_lan_address | ipaddr('address') }}"
          dns-server: "{{ router_dns_servers }}"
    # Calculate target network from IP (ipaddr) > Get current DHCP network config (current_dhcp_network) > Extract 'address' fields only (map) >  Convert to flat list (list) > Check that target network is NOT in that list
      when: (router_lan_address | ipaddr('network/prefix')) not in (current_dhcp_networks.msg | default([]) | map(attribute='address') | list)

    - name: DHCP | Get current IP pools
      community.routeros.api:
        path: "ip pool"
        cmd: "print"
      register: current_pools

    - name: DHCP | Ensure IP pools exists
      community.routeros.api:
        path: "ip pool"
        add:
          name: "dhcp_pool"
          ranges: "{{ router_dhcp_pool }}"
      # Get current DHCP pool (current_pools) > Extract 'name' field only (map) > Convert to flat list (list) > Check that tagret pools is NOT in that list
      when: "'dhcp_pool' not in (current_pools.msg | default([]) | map(attribute='name') | list)"

    - name: DHCP | Get current DHCP servers
      community.routeros.api:
        path: "ip dhcp-server"
        cmd: "print"
      register: "current_dhcp_servers"

    - name: DHCP | Ensure DHCP servers exist
      community.routeros.api:
        path: "ip dhcp-server"
        add:
          name: lab_dhcp
          interface: "{{ router_lan_interface }}"
          address-pool: "dhcp_pool"
          disabled: "false"
        # Get current DHCP servers (current_dhcp_servers) > Extract 'name' fields only (map) > Convert to flat list (list) > Check that DHCP with name 'lan_dhcp' is NOT in that list
      when: "'lab_dhcp' not in (current_dhcp_servers.msg | default([]) | map(attribute='name') | list)"

        # --- 4. SYSTEM IDENTITY ---
    - name: Identity | Get current identity
      community.routeros.api:
        path: "system identity"
        cmd: "print"
      register: current_identity

    - name: Identity | Set router identity
      community.routeros.api:
        path: "system identity"
        update:
          name: "{{ inventory_hostname }}"
      # Set identity if not chosen (inventory_hostneme)
      when: 
        - current_identity.msg | length > 0
        - current_identity.msg[0].name != inventory_hostname

      # --- 5. FIREWALL & NAT ---
    - name: NAT | Get current NAT rules
      community.routeros.api:
         path: "ip firewall nat"
         cmd: "print"
      register: current_nat_rules

    - name: NAT | Ensure Masquerade rule exists
      community.routeros.api:
        path: "ip firewall nat"
        add:
          chain: "srcnat"
          out-interface: "{{ router_wan_interface }}"
          action: "masquerade"
          comment: "Managed by Ansible: LAN access to WAN"
        # Get current rules (current_nat_rules) > Filter only srcnat rules ('chain', 'equalto', 'srcnat') > Filter only masquerade action in rules ('action', 'equalto', 'masquerade') > Find rules binded to actual WAN port ('out-interface', 'equalto', router_wan_interface) > Check all rules list: If rule exists (length > 0), 'not' makes it FALSE -> skip task; If rule missing (length = 0), 'not' makes it TRUE -> add NAT rule
      when: >
        not (current_nat_rules.msg | default([]) | 
        selectattr('chain', 'equalto', 'srcnat') | 
        selectattr('action', 'equalto', 'masquerade') | 
        selectattr('out-interface', 'equalto', router_wan_interface) | list | length > 0)
