---
- name: Set System Identity
  community.routeros.api:
    path: "system identity"
    update: ".id=*0 name={{ inventory_hostname }}"

- name: Ensure DNS is configured
  community.routeros.api:
    path: "ip dns"
    update: "servers=1.1.1.1,8.8.8.8"
