[mikrotiks]
192.168.88.1 ansible_user=admin ansible_password=13311305 ansible_network_os=community.network.routeros ansible_python_interpreter=/home/sandrat/DevOps-Test-Lab/microtik-ansible/.venv/bin/python
