[mikrotik]
192.168.88.1

[mikrotik:vars]
ansible_user=admin
ansible_ssh_pass=""
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=community.routeros.routeros
ansible_network_cli_ssh_type=libssh
# Select the Python3 package inside venv
ansible_python_interpreter=/home/sandrat/DevOps-Test-Lab/ansible-test/venv/bin/python3.13/site-packages
